openapi: 3.1.0
info:
  title: Forma Health API Spec
  description: |
    REST API providing management for user accounts, roles, patient and caregiver profiles, along with topics and clinical studies. Additionally, it facilitates the processing of voice-to-text observations through an advanced Language Model (LLM), structuring them into OMOP (Observational Medical Outcomes Partnership) compliant data for seamless integration and analysis.
  version: 1.0.0
servers:
  - url: https://api-qdmh.onrender.com
tags:
  - name: Test
    description: Test API call
    externalDocs:
        description: Find out more
        url: https://www.formahealth.io/
  - name: Patients
    description: Patients are users who are the subject of observations
  - name: System Measurements
    description: System Measurements are the possible observation input options
  - name: Topics
    description: Topics are categories of observations
  - name: Caregivers
    description: Caregivers are providers of care to a Patient
paths:
  /v1/test:
    get:
      tags:
        - Test
      summary: Test Okta access token
      responses:
        '200': 
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
              examples:
                TestExample:
                  $ref: '#/components/examples/TestExample'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /v1/patients:
    get:
      tags:
        - Patients
      summary: Get all patients for user
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Patient'
                  meta:
                    $ref: '#/components/schemas/Meta'
              examples:
                GetPatientsExample:
                  $ref: '#/components/examples/GetPatientsExample'
        '401':
          $ref: '#/components/responses/Unauthorized'
    post:
      tags:
        - Patients
      summary: Create a new patient
      requestBody:
        $ref: '#/components/requestBodies/NewPatient'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: Patient created successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  /v1/patients/{client_id}:
    get:
      tags:
        - Patients
      summary: Get a patient by ID
      parameters:
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID of the patient to retrieve
      responses:
        '200':
          description: Retrieves detailed information about a specific patient by their ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    schema:
                      $ref: '#/components/schemas/Patient'
              examples:
                GetPatientExample:
                  $ref: '#/components/examples/GetPatientExample'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      tags:
        - Patients
      summary: Update a patient by ID
      parameters:
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID of the patient to update
      requestBody:
        $ref: '#/components/requestBodies/UpdatePatient'
      responses:
        '200':
          description: Updates a patient by their ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Patient updated successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Patients
      summary: Delete a patient by ID
      parameters:
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID of the patient to delete
      responses:
        '200':
          description: Deletes a patient by their ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Patient deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  /v1/measurements:
    get:
      tags:
        - System Measurements
      summary: Get all possible measurements in system
      responses:
        '200':
          description: Retrieves all possible measurements in the system
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Measurement'
              examples:
                GetMeasurementsExample:
                  $ref: '#/components/examples/GetMeasurementsExample'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /v1/measurements/{id}:
    get:
      tags:
        - System Measurements
      summary: Get a measurement by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the measurement to retrieve
      responses:
        '200':
          description: Retrieves detailed information about a specific measurement by its ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    schema:
                      $ref: '#/components/schemas/Measurement'
              examples:
                GetMeasurementExample:
                  $ref: '#/components/examples/GetMeasurementExample'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  /v1/patients/{client_id}/topics:
    get:
      tags:
        - Topics
      summary: Get all topics for a patient
      parameters:
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID of the patient to retrieve topics for
      responses:
        '200':
          description: Retrieves all topics for a specific patient by their ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Topic'
                  meta:
                    $ref: '#/components/schemas/Meta'
              examples:
                GetTopicsExample:
                  $ref: '#/components/examples/GetTopicsExample'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags:
        - Topics
      summary: Add a topic to a patient
      parameters:
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID of the patient to add a topic to
      requestBody:
        $ref: '#/components/requestBodies/NewTopic'
      responses:
        '201':
          description: Adds a topic to a patient
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Topic created successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  /v1/patients/{patient_client_id}/topics/{client_id}:
    get:
      tags:
        - Topics
      summary: Get a Patients Topic by ID
      parameters:
        - in: path
          name: patient_client_id
          schema:
            type: string
          required: true
          description: ID of the patient to retrieve a topic for
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID of the topic to retrieve
      responses:
        '200':
          description: Retrieves detailed information about a specific topic by their ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    schema:
                      $ref: '#/components/schemas/Topic'
              examples:
                GetTopicExample:
                  $ref: '#/components/examples/GetTopicExample'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      tags:
        - Topics
      summary: Update a Patients Topic by ID
      parameters:
        - in: path
          name: patient_client_id
          schema:
            type: string
          required: true
          description: ID of the patient to update a topic for
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID of the topic to update
      requestBody:
        $ref: '#/components/requestBodies/UpdateTopic'
      responses:
        '200':
          description: Updates a topic by their ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Topic updated successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Topics
      summary: Delete a Patients Topic by ID
      parameters:
        - in: path
          name: patient_client_id
          schema:
            type: string
          required: true
          description: ID of the patient to delete a topic for
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID
      responses:
        '200':
          description: Deletes a topic by their ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Topic deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  /v1/patients/{client_id}/caregivers:
    get:
      tags:
        - Caregivers
      summary: Get all caregivers for a patient
      parameters:
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID of the patient to retrieve caregivers for
      responses:
        '200':
          description: Retrieves all caregivers for a specific patient by their ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Caregiver'
                  meta:
                    $ref: '#/components/schemas/Meta'
              examples:
                GetCaregiversExample:
                  $ref: '#/components/examples/GetCaregiversExample'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags:
        - Caregivers
      summary: Add a caregiver to a patient
      parameters:
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID of the patient to add a caregiver to
      requestBody:
        $ref: '#/components/requestBodies/NewCaregiver'
      responses:
        '201':
          description: Adds a caregiver to a patient
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Caregiver created successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  /v1/patients/{patient_client_id}/caregivers/{client_id}:
    get:
      tags:
        - Caregivers
      summary: Get a Patients Caregiver by ID
      parameters:
        - in: path
          name: patient_client_id
          schema:
            type: string
          required: true
          description: ID of the patient to retrieve a caregiver for
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID of the caregiver to retrieve
      responses:
        '200':
          description: Retrieves detailed information about a specific caregiver by their ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    schema:
                      $ref: '#/components/schemas/Caregiver'
              examples:
                GetCaregiverExample:
                  $ref: '#/components/examples/GetCaregiverExample'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      tags:
        - Caregivers
      summary: Update a Patients Caregiver by ID
      parameters:
        - in: path
          name: patient_client_id
          schema:
            type: string
          required: true
          description: ID of the patient to update a caregiver for
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID of the caregiver to update
      requestBody:
        $ref: '#/components/requestBodies/UpdateCaregiver'
      responses:
        '200':
          description: Updates a caregiver by their ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Caregiver updated successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Caregivers
      summary: Delete a Patients Caregiver by ID
      parameters:
        - in: path
          name: patient_client_id
          schema:
            type: string
          required: true
          description: ID of the patient to delete a caregiver for
        - in: path
          name: client_id
          schema:
            type: string
          required: true
          description: ID of the caregiver to delete
      responses:
        '200':
          description: Deletes a caregiver by their ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Caregiver deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
          example:
            errors:
              - title: Unauthorized
                status: 401
                detail: Authorization is required
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
          example:
            errors:
              - title: Bad Request
                status: 401
                detail: Bad request. Please check your request and try again.
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
          example:
            errors:
              - title: Record not found
                status: 404
                detail: We could not find the object you were looking for
  requestBodies:
    NewPatient:
      required: true
      description: A JSON object containing patient information and information about the users relationship to the patient
      content:
        application/json:
          schema:
            type: object
            properties:                
              patient:
                type: object
                properties:
                  client_id:
                    type: string
                    format: uuid
                  first_name:
                    type: string
                  last_name:
                    type: string
                  nickname: 
                    type: string
                  icon_attributes:
                    type: object
                    schema:
                      $ref: '#/components/schemas/Icon'
                  patient_relationship_attributes:
                    type: object
                    properties:
                      relation:
                        type: string
                        format: enum
          examples:
            add patient:
              value:
                patient:
                  client_id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
                  first_name: John
                  last_name: Smith
                  nickname: JS
                  icon_attributes:
                    style: text
                    palette_swatch: red
                    value_text: example_value_text
                    value_emoji: example_value_emoji
                    value_sf_symbol: example_value_sf_symbol
                  patient_relationship_attributes:
                    relation: guardian
            add patient without icon:
              value:
                patient:
                  client_id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
                  nickname: JS
                  patient_relationship_attributes:
                    relation: caregiver
            add self as patient:
              value:
                patient:
                  client_id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
                  first_name: John
                  last_name: Smith
                  nickname: JS
                  icon_attributes:
                    style: text
                    palette_swatch: red
                    value_text: example_value_text
                    value_emoji: example_value_emoji
                    value_sf_symbol: example_value_sf_symbol
                  patient_relationship_attributes:
                    relation: patient
    UpdatePatient:
      content:
        application/json:
          schema:
            type: object
            properties:                
              patient:
                type: object
                properties:
                  client_id:
                    type: string
                    format: uuid
                  first_name:
                    type: string
                  last_name:
                    type: string
                  nickname: 
                    type: string
                  icon_attributes:
                    type: object
                    schema:
                      $ref: '#/components/schemas/Icon'
                  patient_relationship_attributes:
                    type: object
                    properties:
                      relation:
                        type: string
                        format: enum
          examples:
            update patient:
              value:
                patient:
                  nickname: Nate
                  icon_attributes:
                    palette_swatch: blue
                  patient_relationship_attributes:
                    relation: caregiver
            update patient icon:
              value:
                patient:
                  icon_attributes:
                    palette_swatch: blue
            update patient relationship to user:
              value:
                patient:
                  patient_relationship_attributes:
                    relation: partner
    NewCaregiver:
      required: true
      description: A JSON object containing caregiver information and information about the caregivers relationship to the patient
      content:
        application/json:
          schema:
            type: object
            properties:                
              caregiver:
                type: object
                properties:
                  client_id:
                    type: string
                    format: uuid
                  first_name:
                    type: string
                  last_name:
                    type: string
                  nickname: 
                    type: string
                  icon_attributes:
                    type: object
                    schema:
                      $ref: '#/components/schemas/Icon'
                  patient_relationship_attributes:
                    type: object
                    properties:
                      relation:
                        type: string
                        format: enum
          examples:
            add caregiver:
              value:
                caregiver:
                  client_id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
                  first_name: John
                  last_name: Smith
                  nickname: JS
                  icon_attributes:
                    style: text
                    palette_swatch: red
                    value_text: example_value_text
                    value_emoji: example_value_emoji
                    value_sf_symbol: example_value_sf_symbol
                  patient_relationship_attributes:
                    relation: caregiver
            add caregiver without icon:
              value:
                caregiver:
                  client_id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
                  nickname: JS
                  patient_relationship_attributes:
                    relation: coach
    UpdateCaregiver:
      content:
        application/json:
          schema:
            type: object
            properties:                
              caregiver:
                type: object
                properties:
                  client_id:
                    type: string
                    format: uuid
                  first_name:
                    type: string
                  last_name:
                    type: string
                  nickname: 
                    type: string
                  icon_attributes:
                    type: object
                    schema:
                      $ref: '#/components/schemas/Icon'
                  patient_relationship_attributes:
                    type: object
                    properties:
                      relation:
                        type: string
                        format: enum
          examples:
            update caregiver:
              value:
                caregiver:
                  nickname: Nate
                  icon_attributes:
                    palette_swatch: blue
                  patient_relationship_attributes:
                    relation: caregiver
            update caregiver icon:
              value:
                caregiver:
                  icon_attributes:
                    palette_swatch: blue
            update caregiver relationship to user:
              value:
                caregiver:
                  patient_relationship_attributes:
                    relation: spouse
    NewTopic:
      required: true
      description: A JSON object containing topic information
      content:
        application/json:
          schema:
            type: object
            properties:                
              topic:
                type: object
                properties:
                  client_id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  description:
                    type: string
                  icon_attributes:
                    type: object
                    schema:
                      $ref: '#/components/schemas/Icon'
                  measurement_ids:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
          examples:
            add topic:
              value:
                topic:
                  client_id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
                  name: Sleep
                  description: Sleep patterns
                  icon_attributes:
                    style: text
                    palette_swatch: red
                    value_text: example_value_text
                    value_emoji: example_value_emoji
                    value_sf_symbol: example_value_sf_symbol
                  measurement_ids:
                    - id: c737234a-57f2-4cd5-8ab0-6d861e569aed
                    - id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
            add topic without measurements:
              value:
                topic:
                  client_id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
                  name: Sleep
                  description: Sleep patterns
                  icon_attributes:
                    style: text
                    palette_swatch: red
                    value_text: example_value_text
                    value_emoji: example_value_emoji
                    value_sf_symbol: example_value_sf_symbol
            add topic without icon:
              value:
                topic:
                  client_id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
                  name: Sleep
                  description: Sleep patterns
                  measurement_ids:
                    - id: c737234a-57f2-4cd5-8ab0-6d861e569aed
                    - id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
    UpdateTopic:
      content:
        application/json:
          schema:
            type: object
            properties:                
              topic:
                type: object
                properties:
                  client_id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  description:
                    type: string
                  icon_attributes:
                    type: object
                    schema:
                      $ref: '#/components/schemas/Icon'
                  measurement_ids:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        _destroy:
                          type: boolean
          examples:
            update topic:
              value:
                topic:
                  name: Sleep
                  description: Sleep patterns
                  icon_attributes:
                    palette_swatch: blue
            update topic icon:
              value:
                topic:
                  icon_attributes:
                    palette_swatch: blue
            update topic measurements:
              value:
                topic:
                  measurement_ids:
                    - id: c737234a-57f2-4cd5-8ab0-6d861e569aed
                      _destroy: true
  schemas:
    Test:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: object
          properties:
            okta_uid:
              type: string
    Patient:
      type: object
      properties:
        id:
          type: string
          format: uuid
        client_id:
          type: string
          format: uuid
        first_name:
          type: string
        last_name:
          type: string
        nickname: 
          type: string
        updated_at:
          type: integer
          format: int64 UTC Milliseconds
        icon:
          $ref: '#/components/schemas/Icon'
        caregivers:
          type: array
          items:
            $ref: '#/components/schemas/Caregiver'
      required:
        - id
        - client_id
    Caregiver:
      type: object
      properties:
        id:
          type: string
          format: uuid
        client_id:
          type: string
          format: uuid
        first_name:
          type: string
        last_name:
          type: string
        nickname:
          type: string
        relation:
          $ref: '#/components/schemas/Relation'
        updated_at:
          type: integer
          format: int64 UTC Milliseconds
        icon:
          $ref: '#/components/schemas/Icon'
      required:
        - id
        - client_id
    PatientRelationship:
      type: object
      properties:
        id:
          type: string
          format: uuid
        relation:
          $ref: '#/components/schemas/Relation'
        privilege:
          $ref: '#/components/schemas/Privilege'
        patient:
          $ref: '#/components/schemas/Patient'
        care_provider:
          $ref: '#/components/schemas/Caregiver'
      required:
        - id
        - relation
        - privilege
        - patient
        - care_provider
    Measurement:
      type: object
      properties:
        id:
          type: string
          format: uuid
        measurement_type:
          $ref: '#/components/schemas/MeasurementType'
        name:
          type: string
        description:
          type: string
        updated_at:
          type: integer
          format: int64 UTC Milliseconds
        config:
          type: object
    Topic:
      type: object
      properties:
        id:
          type: string
          format: uuid
        client_id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        updated_at:
          type: integer
          format: int64 UTC Milliseconds
        icon:
          $ref: '#/components/schemas/Icon'
        measurements:
          type: array
          items:
            $ref: '#/components/schemas/Measurement'
    Icon:
      type: object
      properties:
        style:
          $ref: '#/components/schemas/Style'
        palette_swatch:
          $ref: '#/components/schemas/PaletteSwatch'
        value_text:
          type: string
        value_emoji:
          type: string
        value_sf_symbol:
          type: string
    Meta:
      type: object
      properties:
        current_page: 
          type: integer
        next_page:
          type: integer
        prev_page:
          type: integer
        totol_pages:
          type: integer
        total_count:
          type: integer
    Error:
      type: object
      properties:
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
    MeasurementType:
      type: string
      enum:
        - unit
        - ordinal_scale
        - nominal_scale
        - binary_scale
        - custom
    Relation:
      type: string
      enum:
        - caregiver
        - patient
        - spouse
        - partner
        - guardian
        - sibling
        - child
        - nanny
        - babysitter
        - friend
        - family_member
        - counselor
        - coach
        - teacher
    Privilege:
      type: string
      enum:
        - standard
        - view
        - edit
        - admin
    Style:
      type: string
      enum:
        - text
        - sf_symbol
        - emoji
        - photo_library
        - camera
    PaletteSwatch:
      type: string
      enum:
        - red
        - orange
        - yellow
        - green
        - mint
        - blue
        - indigo
        - purple
        - pink
        - teal
        - white
        - label
        - symbol_tab
        - disabled
  examples:
    TestExample:
      value:
        success: true
        message: Hello, Kim!
        data:
          okta_uid: example_okta_uid
    IconExample:
      value:
        icon:
          style: text
          palette_swatch: red
          value_text: example_value_text
          value_emoji: example_value_emoji
          value_sf_symbol: example_value_sf_symbol
    GetMeasurementsExample:
      value:
        data:
          - id: c737234a-57f2-4cd5-8ab0-6d861e569aed
            measurement_type: unit
            name: Duration of seizure
            config:
              type: integer
              unit: seconds
              display_unit: minutes_seconds
          - id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
            measurement_type: nominal_scale
            name: Stool size
            config:
              type: string
              options:
                - value: Small
                - value: Medium
                - value: Large
        meta:
          current_page: 1
          next_page: null
          prev_page: null
          total_pages: 1
          total_count: 2
    GetMeasurementExample:
      value:
        data:
          id: c737234a-57f2-4cd5-8ab0-6d861e569aed
          measurement_type: unit
          name: Duration of seizure
          config:
            type: integer
            unit: seconds
            display_unit: minutes_seconds
    GetPatientsExample:
      value:
        data:
          - id: 38734022-af86-473c-8a9a-be7671c9c1fc
            client_id: 5fe55fb7-e69f-49bf-b977-9045e6c63a0c
            first_name: Jessica
            last_name: White
            nickname: JW
            updated_at: 1712270287
            icon:
              style: text
              palette_swatch: red
              value_text: example_value_text
              value_emoji: example_value_emoji
              value_sf_symbol: example_value_sf_symbol
        meta:
          current_page: 1
          next_page: null
          prev_page: null
          total_pages: 1
          total_count: 1
    GetPatientExample:
      value:
        data:
          id: 38734022-af86-473c-8a9a-be7671c9c1fc
          client_id: 5fe55fb7-e69f-49bf-b977-9045e6c63a0c
          first_name: Jessica
          last_name: White
          nickname: JW
          updated_at: 1712270287
          icon:
            style: text
            palette_swatch: red
            value_text: example_value_text
            value_emoji: example_value_emoji
            value_sf_symbol: example_value_sf_symbol
          caregivers:
            - id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
              client_id: cd744f6b-89d4-47a7-8a0e-84f1d6da62bb
              first_name: Jack
              last_name: Black
              nickname: JB
              relation: caregiver
              updated_at: 1712270288
              icon:
                style: text
                palette_swatch: mint
                value_text: example_value_text
                value_emoji: example_value_emoji
                value_sf_symbol: example_value_sf_symbol
    GetCaregiversExample:
      value:
        data:
          - id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
            client_id: cd744f6b-89d4-47a7-8a0e-84f1d6da62bb
            first_name: Jack
            last_name: Black
            nickname: JB
            relation: family_member
            updated_at: 1712270288
            icon:
              style: text
              palette_swatch: mint
              value_text: example_value_text
              value_emoji: example_value_emoji
              value_sf_symbol: example_value_sf_symbol
          - id: 86efba48-0c19-4117-822a-8675f31fba82
            client_id: 906bde4b-1994-4118-acbb-e4ccece9953a
            first_name: Vicki
            last_name: Dooley
            nickname: OW
            relation: babysitter
            updated_at: 1712270289
            icon: null
        meta:
          current_page: 1
          next_page: null
          prev_page: null
          total_pages: 1
          total_count: 2
    GetCaregiverExample:
      value:
        data:
          id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
          client_id: cd744f6b-89d4-47a7-8a0e-84f1d6da62bb
          first_name: Jack
          last_name: Black
          nickname: JB
          relation: caregiver
          updated_at: 1712270288
          icon:
            style: text
            palette_swatch: mint
            value_text: example_value_text
            value_emoji: example_value_emoji
            value_sf_symbol: example_value_sf_symbol
    GetTopicsExample:
      value:
        data:
          - id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
            client_id: 5fe55fb7-e69f-49bf-b977-9045e6c63a0c
            name: Seizure
            description: Seizure observations
            updated_at: 1712270287
            icon:
              style: text
              palette_swatch: red
              value_text: example_value_text
              value_emoji: example_value_emoji
              value_sf_symbol: example_value_sf_symbol
            measurements:
              - id: c737234a-57f2-4cd5-8ab0-6d861e569aed
                measurement_type: unit
                name: Duration of seizure
                config:
                  type: integer
                  unit: seconds
                  display_unit: minutes_seconds
        meta:
          current_page: 1
          next_page: null
          prev_page: null
          total_pages: 1
          total_count: 1
    GetTopicExample:
      value:
        data:
          id: 8e0f94c5-98af-40eb-a162-4a45893fefb7
          client_id: 5fe55fb7-e69f-49bf-b977-9045e6c63a0c
          name: Seizure
          description: Seizure observations
          updated_at: 1712270287
          icon:
            style: text
            palette_swatch: red
            value_text: example_value_text
            value_emoji: example_value_emoji
            value_sf_symbol: example_value_sf_symbol
          measurements:
            - id: c737234a-57f2-4cd5-8ab0-6d861e569aed
              measurement_type: unit
              name: Duration of seizure
              config:
                type: integer
                unit: seconds
                display_unit: minutes_seconds
security:
  - bearerAuth: []
